[package]
name = "minegauler-solver"
version = "0.1.0"
authors = ["Lewis Gaul <lewis.gaul@gmail.com>"]

[lib]
name = "solver"
crate-type = ["cdylib"]

[dependencies]

[build-dependencies]
bindgen = "0.53.2"
