name: Workflow for testing
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ["3.6", "3.7", "3.8"]
    steps:
      - uses: actions/checkout@master

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python requirements
        run: pip install pytest pytest-qt -r requirements.txt

      - name: Set up X-server
        run: |
          sudo apt-get install -y xvfb libxkbcommon-x11-0
          Xvfb :0 &

      - name: Run tests
        env:
          DISPLAY: ":0"
        run: python -m pytest tests/
