name: Workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.6

    - name: Install Python requirements
      run: pip install pytest pytest-cov pytest-qt -r requirements.txt

    - name: Set up X-server
      run: |
        sudo apt-get install -y xvfb
        Xvfb :0 &

    - name: Run tests
      env:
        DISPLAY: ":0"
      run: python -m pytest tests/mut/ --cov . --cov-report xml --cov-report term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: mut
        fail_ci_if_error: true
